docs: add CephObjectStoreUser CR example
galexrt/extended-ceph-exporter pull request #6
Opened 2024-09-27 18:52 UTC by jhoblitt

2024-09-27 19:14 UTC, galexrt requested changes
Thanks for the docs PR! One small comment regarding a potential structure change :smile:

2024-09-27 19:16 UTC, jhoblitt commented on README.md
> +If using Rook to manage rgw, the admin user may also be created using a `CephOjectStoreUser` resource:
That makes sense to me.  I suspect that many users of this exporter are also using rook (as am I).

2024-10-06 18:47 UTC, galexrt commented on README.md
> +If using Rook to manage rgw, the admin user may also be created using a `CephOjectStoreUser` resource:
@jhoblitt Do you want to add the "Rook" section in this PR or should I add it?

2024-10-18 00:30 UTC, closed without merging

2024-10-18 00:30 UTC, galexrt commented
I have added the Rook section to the README based on your text, thanks for providing the instructions!

2024-10-18 00:49 UTC, jhoblitt commented
> I have added the Rook section to the README based on your text, thanks for providing the instructions!

Thank you. I apologize for having not gotten to this. Something had managed to come up every time I was about to look at it.

2024-10-18 14:37 UTC, galexrt commented
No worries, your instructions will definitely help a lot of Rook users get "extended" metrics more easily, thanks! :smile: